// packages/react-ui/src/atoms/Button.tsx
import * as React from "react";

export interface ButtonProps {
  children: React.ReactNode;
  type: String;
  label: String;
}

export const Button: React.FC<ButtonProps> = ({ children = false, type = 'primary', label = 'Button' }) => {
  const handleClick = () => {
    alert("Hello from React UI!");
  }

  return (
    <button className={`button--${type}`} onClick={ () => handleClick() }>
      { children || label }
    </button>
  );
}

Button.displayName = "Button";
export default Button;

// packages/vue-ui/src/atoms/Button.vue
<template>
  <button :class="`button--${type}`" @click="handleClick">
    <slot v-if="hasContentSlot" />
    <span v-else>{{ label }}</span>
  </button>
</template>

<script>
export default{
  props: {
    type: { type: String, default: 'primary' },
    label: { type: String, default: 'Button' },
  },
  methods: {
    handleClick: function(){
      alert("Hello from Vue UI!");
    },
  },
  computed: {
    hasContentSlot: function(){
      return !!this.$slots.default;
    }
  }
}
</script>
